### ISSUE TITLE
reading global vars

### ISSUE THREAD

**Issue by albacoretuna** [maciejjankowski/cheerio-request-webscraper#1]
Hi, 
Using cheerio what's the best way to extract global js vars from an inline script tag? 

I use casper's evaluate for it now, but would switch to cheerio if it were possible to get the same result without using regex.

**Comment by maciejjankowski** [comment]
It depends on what is inside. if it does not rely on the APIs then Javascript eval() might do, if it requires browser's environment and the logic is complicated then casper would be the best bet.

**Comment by albacoretuna** [comment]
Thanks a lot.
